# Generated by Django 4.2.4 on 2023-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_rename_firt_name_contact_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="contact",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
